### ISSUE TITLE
THCState *state = at::globalContext().lazyInitCUDA();

### ISSUE THREAD

**Issue by MichaelCong** [LiuTodd/CenterNet_for_2080ti#1]
Then uncomment the following code:

	//extern THCState *state;
	THCState *state = at::globalContext().lazyInitCUDA();

###THCState *state = at::globalContext().lazyInitCUDA();
this lines not found!
when //extern THCState *state, i got errors。
/home/rencong/CenterNet_for_1080ti/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(97): error: identifier "state" is undefined

/home/rencong/CenterNet_for_1080ti/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_cuda.cu(273): error: identifier "state" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00003eab_00000000-6_dcn_v2_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by MessyPaste** [comment]
Please try deleting the line "//extern THCState *state;".This line is unused
