### ISSUE TITLE
请教一个问题，no module named _ext

### ISSUE THREAD

**Issue by yulei1234** [LiuTodd/CenterNet_for_2080ti#2]
请问这个问题怎么解决呢，linux, 看他们说的win添加环境变量，但好像linux不起作用，反而引起其他的错误，谢谢

**Comment by MessyPaste** [comment]
什么情况下会报这个错？

**Comment by yulei1234** [comment]
我已经解决了这个问题，是因为我没有在anaconda环境中编译，谢谢啦
